### ISSUE TITLE
OPH_PREDICATE: Options for comparison not clear

### ISSUE THREAD

**Issue by TobiasWeigel** [OphidiaBigData/ophidia-analytics-framework#43]
When using oph_rpedicate with comparisons other than '<0' or '>0', an exception is thrown. The reason for the exception is not intuitively visible from the exception text. Looking at the documentation it is also not clear. But the reason is probably that a comparison such as '<10' or '<10.0' is simply not allowed. If this is true, then it should be stated in the docs and the exception should indicate it.

**Comment by minomicetto** [comment]
In next release documentation of the primitive will be extended in order to avoid misuse.
New XML description of the primitive is available from commit https://github.com/OphidiaBigData/ophidia-analytics-framework/commit/6f8876dd326089db7efc6049043d4d709dc8d96b, where the values admitted for argument 'comparison' were added.
See also https://github.com/OphidiaBigData/ophidia-analytics-framework/blob/fix-predicate/etc/primitives_xml/OPH_PREDICATE_primitive_1.0.xml#L25.
